version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: on-failure
    env_file:
      - ./.env
    cap_add:
      - SYS_NICE
    ports:
      - 13306:3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - dev

  laravel:
    build:
      context: ./server
      dockerfile: .docker/Dockerfile
    image: italks-laravel:latest
    container_name: laravel
    restart: on-failure
    volumes:
      - ./server:/var/www/
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - dev
    depends_on:
      - mysql

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./server/public:/usr/share/nginx/html
    ports:
      - 18080:80
    environment:
      - NGINX_BACKEND_PORT=98080
      - NGINX_PORT=80
    networks:
      - dev
    depends_on:
      - laravel
    volumes_from:
      - laravel

  react:
    build:
      context: ./client
      dockerfile: .docker/Dockerfile
    image: italks-react:latest
    container_name: react
    restart: on-failure
    volumes:
      - ./client:/usr/src/app
    ports:
      - 13000:3000
    command: [sh, -c, "cd /usr/src/app ; yarn ; yarn start"]
    networks:
      - dev
    depends_on:
      - mysql

networks:
  dev:

volumes:
  mysql:
